language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: oYN1e3KRdtlMe86dkUs3U1d69rpU9aHl7EzRfTeyPKI7XDTCbjjld92UrzPR93OU/B6B6/8sbxx/qIxQyiJSAmT8Xr43nm6dtJsei8PUdcmg/+bKTyhGmeN90QxRE3so2azzM8MTjiArhEtlRE/AvvS9RQ440yvMi7jedsn+Uv7UMw3ifiYggtWQzwOujgfC52wUvc4aZFCyVA7qzUi8lRcf9Hemk/8ure32hVgWk4gM+BhnLyAwWtxuCvZ12Z7JwuTyiTXZIEZAnNabqw4wkPVRwFNBzncUW/Vo61xzrds3I0zZQ+4Oeq5Q6Xk6iE5cgJ5poBX/0qaxXpwsLPdQ13C8eW2G1EEH4Dt5O3PyYhMY/znWrHfccNMeFI/DjNejh1kufv2uJQEHYTMh3ujoMNuP3osnX//ixhzrWSac7Cnzu1FG+u3rbOzq8UWFslXRWo2+y0/dBcNeKjW27sydrRcKDMBr6FXNkxvyO1JMZ864Ro+9UQeCWi0CH0CEQCbMN5fYkBJGD7aG069/mFKwv1G0QZDvj03cf4Nyw4kPmYaQqoeS6jiUWng0JuHX+w+zX4KaJfMquOHcYMMV6Io8pYPNqtHD5aAt/YLUZrYQx88EnEMYFen9vL8B+nPG8KYodfEmai4Z09G0qJ4Cv+07al28nWX18LYnUiM/FTOQxOw=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: d774Yp3pwMVIy9CwW0BGMrNduXj7/3yXHg2/NVEac+A9fYD0QZ0K0kh+NFdQ1495eNWx3TJlbpiRKbQjrUucenXAnyHB9XkkRDSSTx09C9rngMXHdk8dEsSSWg84EpX7mxOPznhs/IuCiQ5FLfnCArYRYFX8Zpq8aT5lNWphDzUGDH+8sMITaw+4zKxaCiftMrkcdj70RWj01zOoe0VgXh6WCwchZ5V8IzHQmJN+1CcSEJoDRFGzk3fNezUZG6XzIo0xwxM61CeXqOiNG+6NSmRicGNcHvE12LMoLGUv7fzosNG1YKdW7aDQ88C+1KuPhFj6k9h7OoyBHXcoQuMCCZHnCk7ZPuEMTWpJfY44QKHOORnqc2HTVe2NC3IOeSoBmCPQfe0T4cWx7mdaBigzVyLsL9MChamAo/Coy8U5kKf033X89kzwI0yUBr25k+DOR0f7wNo8yj2dwssTsO3GgMbaM+8lh4TClOTabISB0rXZhUM6DwnxyhWBlXAqcj/QijaJ9oERhA3ltRdD2H86D8KmVa7BZMDTmzwkfZ8zmEKC7Sv1OF3bC5otGumpUrx4poRV7QdVomGKPsT5MlmTHppRy4sX5CjFwbNTrEACEg+oNsKapH1BojclbLukDAH8jk5MoD7oNykaDoJotht2XclQ5GHxzC4LQdBuod2Mpj4=
sudo: false
