language: node_js
node_js:
- '0.12'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
deploy:
  provider: npm
  email: mvila@3base.com
  api_key:
    secure: aVXTKvQtpDwP54KIPebTfuwIjGiE+YlhD8MGv3dyi7DHQSzbS4JWvtNLlrThtHVaOlFQT/7959/aMCIacEvAO7e0n5O4I/0bPoj0aCUEHOJ3FfMcSPRaOBtUaddyA4i+4P3Zfxa3OyEapMo6pRX9K+TiC0Ae1NsyXHLNtII49nWvd8SaMvBEJzehWPdDZWuZFzy15KCllh5rcNMHSWkG5EinmwTt+JDA824oXe1F6s6Gkd9TGvYLBomz7mXi9o8gNMZBFROlnp2vUyOrAZ1l2+CS9i+GDkE3mkQQZGBPpp++/sN1LkwwPSnA1dg6ZnoLs9i+T2e9vJCm+JCHP1r/ONG4iUsrvQN0CihDefeO6BB0xMRlTHWJVGY4+j3BPy/F0b9Mxbe0W20TpQvAMNrXxHRX+WKManDbmldPcj4gfBMqShLgWHwJQ1SO+bYH4u6JaXUGc6AC3p6UVTlMymeZwcY1dw4BPgnu/thqsPBXcBLozNFYny6zKrDefzFNj053flS0bEcDsTByen9WKW7MR7N8UdVGdTqjfs8sKUufSbCpJv3wMXjQ81KFBBXhcgsSMoVK6QvLiFTuKsB6ANJO7FtmCGiQ7XsngJESf16xTdH8YUiTYqyo4r95b7YyyGdf3BE6D0JneXZrYKz4iKbk6Wn3bFYDs7NcbY/VByXYb+4=
  skip_cleanup: true
notifications:
  email: false
  slack:
    secure: d774Yp3pwMVIy9CwW0BGMrNduXj7/3yXHg2/NVEac+A9fYD0QZ0K0kh+NFdQ1495eNWx3TJlbpiRKbQjrUucenXAnyHB9XkkRDSSTx09C9rngMXHdk8dEsSSWg84EpX7mxOPznhs/IuCiQ5FLfnCArYRYFX8Zpq8aT5lNWphDzUGDH+8sMITaw+4zKxaCiftMrkcdj70RWj01zOoe0VgXh6WCwchZ5V8IzHQmJN+1CcSEJoDRFGzk3fNezUZG6XzIo0xwxM61CeXqOiNG+6NSmRicGNcHvE12LMoLGUv7fzosNG1YKdW7aDQ88C+1KuPhFj6k9h7OoyBHXcoQuMCCZHnCk7ZPuEMTWpJfY44QKHOORnqc2HTVe2NC3IOeSoBmCPQfe0T4cWx7mdaBigzVyLsL9MChamAo/Coy8U5kKf033X89kzwI0yUBr25k+DOR0f7wNo8yj2dwssTsO3GgMbaM+8lh4TClOTabISB0rXZhUM6DwnxyhWBlXAqcj/QijaJ9oERhA3ltRdD2H86D8KmVa7BZMDTmzwkfZ8zmEKC7Sv1OF3bC5otGumpUrx4poRV7QdVomGKPsT5MlmTHppRy4sX5CjFwbNTrEACEg+oNsKapH1BojclbLukDAH8jk5MoD7oNykaDoJotht2XclQ5GHxzC4LQdBuod2Mpj4=
sudo: false
